/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'crm-accounts': CrmAccountAuthOperations;
    'client-accounts': ClientAccountAuthOperations;
  };
  blocks: {};
  collections: {
    'page-seo': PageSeo;
    posts: Post;
    media: Media;
    categories: Category;
    'website-showcase': WebsiteShowcase;
    testimonials: Testimonial;
    users: User;
    clients: Client;
    'crm-accounts': CrmAccount;
    'client-accounts': ClientAccount;
    contacts: Contact;
    projects: Project;
    invoices: Invoice;
    payments: Payment;
    tasks: Task;
    'project-requests': ProjectRequest;
    conversations: Conversation;
    messages: Message;
    resources: Resource;
    notifications: Notification;
    enquiries: Enquiry;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'page-seo': PageSeoSelect<false> | PageSeoSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'website-showcase': WebsiteShowcaseSelect<false> | WebsiteShowcaseSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'crm-accounts': CrmAccountsSelect<false> | CrmAccountsSelect<true>;
    'client-accounts': ClientAccountsSelect<false> | ClientAccountsSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    'project-requests': ProjectRequestsSelect<false> | ProjectRequestsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | CrmAccount | ClientAccount;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CrmAccountAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ClientAccountAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage the SEO metadata for each hardcoded page. Create one record per page using the URL slug as the identifier.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-seo".
 */
export interface PageSeo {
  id: number;
  /**
   * The URL path for the page. Use "/" for the home page, "about" for /about, etc.
   */
  pageSlug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * Prevent search engines from indexing this page (adds noindex,nofollow).
   */
  noindex?: boolean | null;
  /**
   * Override the canonical URL for this page. Leave blank to use the default URL.
   */
  canonicalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Super admin: everything, and cannot be demoted by an admin. Admin: content, settings and inviting editors. Editor: content only.
   */
  role: 'superAdmin' | 'admin' | 'editor';
  /**
   * Provisioned from ADMIN_EMAIL. Its password is reset from the environment on every restart, so change it there rather than here.
   */
  isEnvManaged?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Live client sites shown under the homepage hero. Add the URL and publish it, then run `pnpm capture:showcase` to fetch the screenshot and check whether the site allows being embedded. A site with no screenshot yet is skipped rather than shown broken.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-showcase".
 */
export interface WebsiteShowcase {
  id: number;
  /**
   * Shown on the card. e.g. "Create A Content".
   */
  title: string;
  /**
   * The card links here and the live preview loads it.
   */
  url: string;
  /**
   * Optional. What the fake browser bar shows. Defaults to the hostname.
   */
  displayUrl?: string | null;
  /**
   * Chip shown on the card.
   */
  category?: ('website' | 'webApp' | 'ecommerce' | 'landing' | 'content' | 'other') | null;
  /**
   * Filled in by `pnpm capture:showcase` — a full-page screenshot at 1440px wide. This is both the placeholder and the fallback, so a site with no poster is not shown at all.
   */
  poster?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * Off until you are happy with the screenshot.
   */
  published?: boolean | null;
  /**
   * Sorts to the front, above the order number.
   */
  featured?: boolean | null;
  /**
   * Controls the hover-scroll live preview. Status and page height are written by the capture script — you only need to touch the mode.
   */
  embed: {
    /**
     * Switch to "Screenshot only" for any site with a cookie banner, a full-screen hero, or heavy ads — those look wrong inside a small frame. The screenshot still scrolls, so the card loses nothing visually.
     */
    mode: 'auto' | 'live' | 'poster';
    /**
     * From the site’s X-Frame-Options / CSP headers at capture time.
     */
    status?: ('unknown' | 'allowed' | 'blocked') | null;
    /**
     * Which header produced that verdict.
     */
    reason?: string | null;
    checkedAt?: string | null;
    /**
     * How tall the embedded page renders, in pixels — and therefore how far the hover scroll can travel. Lower it to about 1500 for sites whose hero fills the whole screen, otherwise the preview shows nothing but that hero.
     */
    viewportHeight?: number | null;
    /**
     * Real height of the full page at 1440px wide, measured during capture.
     */
    pageHeight?: number | null;
  };
  /**
   * Written by `pnpm capture:showcase`.
   */
  capture?: {
    lastCapturedAt?: string | null;
    error?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Client reviews for the strip under the homepage hero. Publish at least four and the section switches from the built-in placeholder reviews to yours — it is all or nothing, so a half-filled section can never ship by accident.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * What they said, in their words. Two or three sentences — the cards are narrow and they scroll past, so anything longer is never finished.
   */
  quote: string;
  /**
   * Who said it. e.g. "Briana Patton".
   */
  name: string;
  /**
   * Their title and company, shown under the name. e.g. "Operations Manager".
   */
  role?: string | null;
  /**
   * Stars, 1 to 5.
   */
  rating: number;
  /**
   * Optional. Without one the card shows their initials in the accent colour.
   */
  avatar?: (number | null) | Media;
  /**
   * Unpublished reviews are invisible to the public API, not just the page.
   */
  published?: boolean | null;
  /**
   * Lower numbers come first. Ties fall back to newest.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  /**
   * Generated on create — quote it in email.
   */
  code?: string | null;
  status?: ('lead' | 'proposal' | 'active' | 'onHold' | 'former') | null;
  /**
   * Team members who look after this client. A member sees every project of a client they are on.
   */
  assignedTo?: (number | CrmAccount)[] | null;
  website?: string | null;
  email?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  address?: string | null;
  /**
   * Team only — not visible in the client portal.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-accounts".
 */
export interface CrmAccount {
  id: number;
  name?: string | null;
  /**
   * Admin manages accounts and billing. Manager runs clients and projects. Member sees assigned work.
   */
  role: 'admin' | 'manager' | 'member';
  /**
   * Provisioned from CRM_ADMIN_EMAIL. Manage its password in the environment.
   */
  isEnvManaged?: boolean | null;
  /**
   * Suspends the account without deleting it. Enforced in access control, not just hidden in the UI — a paused session can read and write nothing.
   */
  isPaused?: boolean | null;
  /**
   * Shown next to their name on assignments.
   */
  jobTitle?: string | null;
  /**
   * For SMS one-time codes (not yet enabled).
   */
  phone?: string | null;
  provider?: ('password' | 'google') | null;
  /**
   * Google subject id — binds one Google identity to this account so logins are not re-matched by email each time.
   */
  providerAccountId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'crm-accounts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-accounts".
 */
export interface ClientAccount {
  id: number;
  name?: string | null;
  /**
   * The company this dashboard login belongs to.
   */
  client: number | Client;
  /**
   * Signups start pending and see a waiting screen. Only your team can move an account to active.
   */
  approvalStatus: 'pending' | 'active' | 'paused' | 'rejected';
  jobTitle?: string | null;
  organization?: string | null;
  /**
   * For SMS one-time codes (not yet enabled).
   */
  phone?: string | null;
  whatsapp?: string | null;
  address?: string | null;
  bio?: string | null;
  deletionRequested?: boolean | null;
  deletionRequestedAt?: string | null;
  deletionReason?: string | null;
  provider?: ('password' | 'google') | null;
  providerAccountId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'client-accounts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  name: string;
  client: number | Client;
  email?: string | null;
  phone?: string | null;
  jobTitle?: string | null;
  isPrimary?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  /**
   * Generated on create — quote it in email.
   */
  code?: string | null;
  client: number | Client;
  status?:
    | ('pendingApproval' | 'notStarted' | 'planning' | 'inProgress' | 'review' | 'completed' | 'onHold' | 'cancelled')
    | null;
  /**
   * Team members put on this project. Drives what they can see.
   */
  assignedTo?: (number | CrmAccount)[] | null;
  startDate?: string | null;
  dueDate?: string | null;
  /**
   * Agreed project value, in minor units (e.g. pence).
   */
  value?: number | null;
  summary?: string | null;
  /**
   * What is included. Shown to the client on their project page.
   */
  scopeOfWork?: string | null;
  /**
   * Team only — never rendered in the client portal.
   */
  internalNotes?: string | null;
  /**
   * Deliverables and attachments. Reuses the existing R2-backed media.
   */
  files?: (number | Media)[] | null;
  /**
   * Custom columns shown on this project’s task board.
   */
  taskColumns?:
    | {
        /**
         * Stable id used to store values. Do not change it once in use.
         */
        key: string;
        label: string;
        type: 'text' | 'number' | 'dropdown' | 'checkbox' | 'doc' | 'sheet' | 'snap' | 'drive' | 'website';
        /**
         * Choices for a dropdown column.
         */
        options?:
          | {
              value: string;
              tone?: ('neutral' | 'info' | 'success' | 'warning' | 'danger') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  number: string;
  client: number | Client;
  project?: (number | null) | Project;
  status?: ('draft' | 'sent' | 'paid' | 'overdue' | 'void') | null;
  issueDate?: string | null;
  dueDate?: string | null;
  currency?: string | null;
  lineItems?:
    | {
        description: string;
        quantity: number;
        /**
         * In minor units — 12345 means £123.45.
         */
        unitAmount: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Percent, e.g. 20.
   */
  taxRate?: number | null;
  subtotal?: number | null;
  tax?: number | null;
  total?: number | null;
  notes?: string | null;
  /**
   * Set by Stripe once online payments are enabled.
   */
  stripeInvoiceId?: string | null;
  stripeStatus?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  reference?: string | null;
  invoice: number | Invoice;
  /**
   * Denormalised from the invoice so portal access can be filtered in SQL without a join.
   */
  client: number | Client;
  /**
   * In minor units, matching the invoice currency.
   */
  amount: number;
  paidAt?: string | null;
  method?: ('bankTransfer' | 'card' | 'cash' | 'other') | null;
  notes?: string | null;
  stripePaymentId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  title: string;
  project: number | Project;
  status?: ('todo' | 'inProgress' | 'blocked' | 'done') | null;
  priority?: ('low' | 'normal' | 'high') | null;
  assignee?: (number | null) | CrmAccount;
  dueDate?: string | null;
  notes?: string | null;
  /**
   * Percent complete, for work that is not simply done or not done.
   */
  progress?: number | null;
  links?:
    | {
        label: string;
        url: string;
        kind?: ('doc' | 'sheet' | 'snap' | 'drive' | 'website') | null;
        id?: string | null;
      }[]
    | null;
  subtasks?:
    | {
        title: string;
        status?: ('todo' | 'inProgress' | 'blocked' | 'done') | null;
        priority?: ('low' | 'normal' | 'high') | null;
        assignee?: (number | null) | CrmAccount;
        dueDate?: string | null;
        /**
         * Values for this project’s custom columns, keyed by column id.
         */
        fields?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-requests".
 */
export interface ProjectRequest {
  id: number;
  title: string;
  client: number | Client;
  details?: string | null;
  status?: ('new' | 'review' | 'accepted' | 'declined') | null;
  project?: (number | null) | Project;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: number;
  subject: string;
  /**
   * Empty for mail from someone without a portal account.
   */
  client?: (number | null) | Client;
  contactName?: string | null;
  contactEmail?: string | null;
  mailbox?: ('support' | 'sales' | 'info' | 'billing' | 'contact' | 'other') | null;
  folder: 'inbox' | 'archived' | 'trash';
  /**
   * Unread by your team — cleared when a teammate opens it.
   */
  unread?: boolean | null;
  lastMessageAt?: string | null;
  lastMessagePreview?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  conversation?: (number | null) | Conversation;
  /**
   * Empty for mail from someone with no portal account.
   */
  client?: (number | null) | Client;
  project?: (number | null) | Project;
  body: string;
  authorType: 'staff' | 'client';
  authorName?: string | null;
  direction?: ('inbound' | 'outbound') | null;
  fromEmail?: string | null;
  toEmail?: string | null;
  /**
   * The provider's message id, for threading replies.
   */
  externalId?: string | null;
  readByStaff?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  label: string;
  client: number | Client;
  project?: (number | null) | Project;
  kind?: ('link' | 'file' | 'screen' | 'doc' | 'drive' | 'custom') | null;
  /**
   * Heading to group under, for the custom kind.
   */
  section?: string | null;
  /**
   * Shown under a screen preview.
   */
  caption?: string | null;
  url?: string | null;
  file?: (number | null) | Media;
  /**
   * Lower sorts first.
   */
  order?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipientType: 'staff' | 'client';
  staffRecipient?: (number | null) | CrmAccount;
  clientRecipient?: (number | null) | ClientAccount;
  type:
    | 'general'
    | 'projectRequested'
    | 'projectApproved'
    | 'projectDeclined'
    | 'projectCreated'
    | 'projectStatusChanged'
    | 'taskAdded'
    | 'taskUpdated'
    | 'invoiceIssued'
    | 'invoiceUpdated'
    | 'paymentRecorded'
    | 'accessRequested'
    | 'accessApproved'
    | 'accessRejected'
    | 'deletionRequested'
    | 'messageReceived'
    | 'resourceShared';
  title: string;
  message?: string | null;
  /**
   * In-app path the bell sends you to, e.g. /crm/requests.
   */
  link?: string | null;
  read?: boolean | null;
  /**
   * Ids and names the notification was built from.
   */
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  /**
   * What the visitor was doing. Add a value here when a new form goes live — nothing else needs to change.
   */
  kind: 'contact' | 'message' | 'pricing' | 'quote' | 'callback' | 'other';
  status: 'new' | 'inProgress' | 'responded' | 'won' | 'closed' | 'spam';
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  company?: string | null;
  subject?: string | null;
  message?: string | null;
  /**
   * Anything a specific form collects beyond the fields above — budget, services, timeline. Kept as JSON so a new form needs no migration.
   */
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The page it was submitted from.
   */
  source?: string | null;
  /**
   * Who is answering this.
   */
  assignedTo?: (number | null) | CrmAccount;
  /**
   * Set when an enquiry is turned into a client.
   */
  client?: (number | null) | Client;
  internalNotes?: string | null;
  respondedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'page-seo';
        value: number | PageSeo;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'website-showcase';
        value: number | WebsiteShowcase;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'crm-accounts';
        value: number | CrmAccount;
      } | null)
    | ({
        relationTo: 'client-accounts';
        value: number | ClientAccount;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'project-requests';
        value: number | ProjectRequest;
      } | null)
    | ({
        relationTo: 'conversations';
        value: number | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'crm-accounts';
        value: number | CrmAccount;
      }
    | {
        relationTo: 'client-accounts';
        value: number | ClientAccount;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'crm-accounts';
        value: number | CrmAccount;
      }
    | {
        relationTo: 'client-accounts';
        value: number | ClientAccount;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-seo_select".
 */
export interface PageSeoSelect<T extends boolean = true> {
  pageSlug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  noindex?: T;
  canonicalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-showcase_select".
 */
export interface WebsiteShowcaseSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  displayUrl?: T;
  category?: T;
  poster?: T;
  sortOrder?: T;
  published?: T;
  featured?: T;
  embed?:
    | T
    | {
        mode?: T;
        status?: T;
        reason?: T;
        checkedAt?: T;
        viewportHeight?: T;
        pageHeight?: T;
      };
  capture?:
    | T
    | {
        lastCapturedAt?: T;
        error?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  rating?: T;
  avatar?: T;
  published?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  isEnvManaged?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  status?: T;
  assignedTo?: T;
  website?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  address?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-accounts_select".
 */
export interface CrmAccountsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  isEnvManaged?: T;
  isPaused?: T;
  jobTitle?: T;
  phone?: T;
  provider?: T;
  providerAccountId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-accounts_select".
 */
export interface ClientAccountsSelect<T extends boolean = true> {
  name?: T;
  client?: T;
  approvalStatus?: T;
  jobTitle?: T;
  organization?: T;
  phone?: T;
  whatsapp?: T;
  address?: T;
  bio?: T;
  deletionRequested?: T;
  deletionRequestedAt?: T;
  deletionReason?: T;
  provider?: T;
  providerAccountId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  name?: T;
  client?: T;
  email?: T;
  phone?: T;
  jobTitle?: T;
  isPrimary?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  client?: T;
  status?: T;
  assignedTo?: T;
  startDate?: T;
  dueDate?: T;
  value?: T;
  summary?: T;
  scopeOfWork?: T;
  internalNotes?: T;
  files?: T;
  taskColumns?:
    | T
    | {
        key?: T;
        label?: T;
        type?: T;
        options?:
          | T
          | {
              value?: T;
              tone?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  number?: T;
  client?: T;
  project?: T;
  status?: T;
  issueDate?: T;
  dueDate?: T;
  currency?: T;
  lineItems?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitAmount?: T;
        id?: T;
      };
  taxRate?: T;
  subtotal?: T;
  tax?: T;
  total?: T;
  notes?: T;
  stripeInvoiceId?: T;
  stripeStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  reference?: T;
  invoice?: T;
  client?: T;
  amount?: T;
  paidAt?: T;
  method?: T;
  notes?: T;
  stripePaymentId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  title?: T;
  project?: T;
  status?: T;
  priority?: T;
  assignee?: T;
  dueDate?: T;
  notes?: T;
  progress?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        kind?: T;
        id?: T;
      };
  subtasks?:
    | T
    | {
        title?: T;
        status?: T;
        priority?: T;
        assignee?: T;
        dueDate?: T;
        fields?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-requests_select".
 */
export interface ProjectRequestsSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  details?: T;
  status?: T;
  project?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  subject?: T;
  client?: T;
  contactName?: T;
  contactEmail?: T;
  mailbox?: T;
  folder?: T;
  unread?: T;
  lastMessageAt?: T;
  lastMessagePreview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversation?: T;
  client?: T;
  project?: T;
  body?: T;
  authorType?: T;
  authorName?: T;
  direction?: T;
  fromEmail?: T;
  toEmail?: T;
  externalId?: T;
  readByStaff?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  label?: T;
  client?: T;
  project?: T;
  kind?: T;
  section?: T;
  caption?: T;
  url?: T;
  file?: T;
  order?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipientType?: T;
  staffRecipient?: T;
  clientRecipient?: T;
  type?: T;
  title?: T;
  message?: T;
  link?: T;
  read?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  kind?: T;
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  subject?: T;
  message?: T;
  details?: T;
  source?: T;
  assignedTo?: T;
  client?: T;
  internalNotes?: T;
  respondedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact channels shown in the site header and on the contact page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Shown as-is and dialled on tap. Write it how you want it read, e.g. +44 20 1234 5678.
   */
  phone?: string | null;
  /**
   * Full international number, e.g. +44 20 1234 5678. Spaces and symbols are stripped for the link, so type it however you like. Often the same as the phone number, but it does not have to be.
   */
  whatsapp?: string | null;
  /**
   * Pre-filled in the chat so you know which page they came from. Leave empty for a blank chat.
   */
  whatsappMessage?: string | null;
  /**
   * Falls back to the address in site config when empty.
   */
  email?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  whatsapp?: T;
  whatsappMessage?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}